### ISSUE TITLE
Query is malformed: Encountered " <INTEGER> "5960338859003578441 "" at line 1, column 1.

### ISSUE THREAD

**Issue by dretta** [database-of-embassies/database-of-embassies#22]
![](http://i.imgur.com/rQUvt78.png)

**Comment by nicolas-raoul** [comment]
Thanks for the feedback!
I tested it and it works for me here, very strange.

Could you include the whole browser window in your screenshot, include even the URL bar? It might give a few hints. Thanks!

**Comment by nicolas-raoul** [comment]
@dretta Does this still happen?

**Comment by dretta** [comment]
Nope :)

**Comment by nicolas-raoul** [comment]
Thanks for testing! :-)
