### ISSUE TITLE
Query Timeout Reached 

### ISSUE THREAD

**Issue by ericoulster** [database-of-embassies/database-of-embassies#40]
For any of the different queries, I am getting an error with execution, and receiving no data.

Attached is a screenshot
![81176635-682cd100-8f73-11ea-9d43-15aefebf6fb8](https://user-images.githubusercontent.com/40222141/81255435-9c4bd480-8ffb-11ea-95e7-7dfd279feffe.png)

(This issue is copied from its mention in an unrelated bug report on the same project)

**Comment by nicolas-raoul** [comment]
Indeed the main query reaches time out... maybe the solution would be to split the query per operating country, for instance I think that the [query for embassies operated by Japan](https://query.wikidata.org/#SELECT%20DISTINCT%0A%09%28SAMPLE%28%3Fcountry_label%29%20as%20%3Fcountry%29%09%28SAMPLE%28%3Fcity_label%29%20as%20%3Fcity%29%09%28SAMPLE%28%3Faddress%29%20as%20%3Faddress%29%09%28SAMPLE%28%3Fcoordinates%29%20as%20%3Fcoordinates%29%0A%09%28SAMPLE%28%3Foperator_label%29%20as%20%3Foperator%29%09%28SAMPLE%28%3Ftype_label%29%20as%20%3Ftype%29%09%28SAMPLE%28%3Fphone%29%20as%20%3Fphone%29%09%09%28SAMPLE%28%3Femail%29%20as%20%3Femail%29%0A%09%28SAMPLE%28%3Fwebsite%29%20as%20%3Fwebsite%29%09%09%09%28SAMPLE%28%3Fimage%29%20as%20%3Fimage%29%09%09%3Fwikidata%0A%09%28SAMPLE%28%3Ffacebook%29%20as%20%3Ffacebook%29%20%28SAMPLE%28%3Ftwitter%29%20as%20%3Ftwitter%29%20%28SAMPLE%28%3Fyoutube%29%20as%20%3Fyoutube%29%20%28SAMPLE%28%3Finception%29%20as%20%3Finception%29%0AWHERE%20%7B%0A%09%7B%20%3Fwikidata%20p%3AP31%2Fps%3AP31%2Fwdt%3AP279%2a%20wd%3AQ3917681.%20%7D%20UNION%20%7B%20%3Fwikidata%20p%3AP31%2Fps%3AP31%2Fwdt%3AP279%2a%20wd%3AQ5244910.%20%7D%20UNION%20%7B%3Fwikidata%20p%3AP31%2Fps%3AP31%2Fwdt%3AP279%2a%20wd%3AQ7843791.%7D%20UNION%20%7B%3Fwikidata%20p%3AP31%2Fps%3AP31%2Fwdt%3AP279%2a%20wd%3AQ61881945%7D%20%23%20Any%20type%20of%20embassy%20or%20consulate%0A%09%3Fwikidata%20p%3AP31%2Fps%3AP31%20%3FtypeId.%20%3FtypeId%20wdt%3AP279%2a%20wd%3AQ43229.%20%3FtypeId%20rdfs%3Alabel%20%3Ftype_label.%20FILTER%20%28lang%28%3Ftype_label%29%20%3D%20%22en%22%29.%0A%09%3Fwikidata%20wdt%3AP131%2a%20%3Farea%20.%0A%09%3Farea%20wdt%3AP17%20%3FcountryId.%20%3FcountryId%20rdfs%3Alabel%20%3Fcountry_label.%20FILTER%20%28lang%28%3Fcountry_label%29%20%3D%20%22en%22%29.%0A%09%7B%3Fwikidata%20wdt%3AP137%20wd%3AQ17.%7D%0A%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP131%20%3FcityId.%20%3FcityId%20rdfs%3Alabel%20%3Fcity_label.%20FILTER%20%28lang%28%3Fcity_label%29%20%3D%20%22en%22%29.%7D%0A%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP969%20%3Faddress.%7D%09%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP625%20%3Fcoordinates.%7D%0A%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP1329%20%3Fphone.%7D%09%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP968%20%3Femail.%7D%0A%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP856%20%3Fwebsite.%7D%09%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP18%20%3Fimage.%7D%0A%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP2013%20%3Ffacebook.%7D%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP2002%20%3Ftwitter.%7D%0A%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP2397%20%3Fyoutube.%7D%09OPTIONAL%20%7B%3Fwikidata%20wdt%3AP571%20%3Finception.%7D%0A%09MINUS%20%7B%3Fwikidata%20wdt%3AP582%20%3Fendtime.%7D%09%20MINUS%20%7B%3Fwikidata%20wdt%3AP582%20%3FdissolvedOrAbolished.%7D%0A%09MINUS%20%7B%3Fwikidata%20p%3AP31%20%3FinstanceStatement.%20%3FinstanceStatement%20pq%3AP582%20%3FendtimeQualifier.%7D%0A%09%23%20Only%20countries%20that%20still%20contain%20the%20location%20%28ex%3A%20Pristina%20is%20not%20in%20the%20%22Province%20of%20Kosovo%22%20because%20it%20does%20not%20exist%20anymore.%0A%09FILTER%20NOT%20EXISTS%20%7B%0A%09%09%3Fwikidata%20p%3AP131%2F%28ps%3AP131%2Fp%3AP131%29%2a%20%3Fstatement.%0A%09%09%3Fstatement%20ps%3AP131%20%3Farea.%0A%09%09%3Fwikidata%20p%3AP131%2F%28ps%3AP131%2Fp%3AP131%29%2a%20%3FintermediateStatement.%0A%09%09%3FintermediateStatement%20%28ps%3AP131%2Fp%3AP131%29%2a%20%3Fstatement.%0A%09%09%3FintermediateStatement%20pq%3AP582%20%3FendTime.%0A%09%7D%0A%7D%20GROUP%20BY%20%3Fwikidata%20ORDER%20BY%20ASC%28%3Fcountry%29%20ASC%28%3Fcity%29%20ASC%28%3Foperator%29%20DESC%28%3Ftype%29) works always (need to verify for other countries). A Python script could stitch the results. We could set up a script and cron on the tools server.

**Comment by nicolas-raoul** [comment]
@ericoulster I fixed the issue by splitting into different queries and having a Python script generate the output (as a CSV file). I hope it solves the problem :-) Thanks for reporting!
