### ISSUE TITLE
Ignore dissolved countries

### ISSUE THREAD

**Issue by nicolas-raoul** [database-of-embassies/database-of-embassies#45]
P576

In all requests.

Example: https://www.wikidata.org/wiki/Q713750 West Germany

**Comment by mccallc** [comment]
Examples:
http://www.wikidata.org/entity/Q19383606 Norway -> GDR
http://www.wikidata.org/entity/Q72237312 France -> Soviet Union

**Comment by nicolas-raoul** [comment]
@mccallc Thanks for the feedback! I will try to fix that now.

**Comment by nicolas-raoul** [comment]
I think I fixed the problem in this commit: https://github.com/database-of-embassies/database-of-embassies/commit/58b7f0e23597ac43ea9ae02730bd116cb33d3aec
Would you mind checking?
Thanks!

**Comment by mccallc** [comment]
Yes, this fix worked great! Thanks!
